site_name: DataPull Documentation
site_description: 'Open Source Docs and Community Standards'
site_author: 'Data Tools'
repo_name: 'datapull'
edit_uri: 'edit/master/docs/'
theme:
    name: 'material'
nav:
    - Home: index.md
    - Architecture: architecture.md
    - EMR Runbook: emr_runbook.md
    - Qubole Runbook : qubole_runbook.md
    - Sample JSON of using Join operation: join_operation.md
    - Sample JSON of using SQL Transformation in Data Pull Json: transformation.md
    - Securely accessing data for DataPull: securely_accessing_data.md
    - FAQ: faq.md
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.magiclink
    - meta
    - codehilite
extra_css:
    - extra.css

extra:
  repo_url: ''

plugins:
    - markdownextradata